development:
  sessions:
    default:
      database: facebook_pages_fetcher_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: facebook_pages_fetcher_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
